grammar at.jku.weiner.xtexttest.XtextTest with org.eclipse.xtext.common.Terminals

import "http://www.eclipse.org/emf/2002/Ecore" as ecore

generate xtextTest "http://www.jku.at/weiner/xtexttest/XtextTest"

XtextTest:
	{XtextTest}
	PACKAGE package=PackageID
	LANGUAGE lang=LangID
	input=Input
	(tokens=Tokens)?
	root=Element
;

PackageID returns ecore::EString:
	IDENTIFIER (POINT IDENTIFIER)*
;

LangID returns ecore::EString:
	IDENTIFIER
;

Input:
	{Input}
	SOURCE
	(SRCTEXT ASSIGNASSINGLE text=STRING
	|SRCFILE ASSIGNASSINGLE file=STRING
	)
;

Tokens:
	{Tokens}
	LEXER
	(tokens+=IDENTIFIER)+
;

Element:
	{Element}
	LEFTPAREN
		name=IDENTIFIER
		(
			(inner+=Inner)
			(COMMA inner+=Inner)?
		)?
	RIGHTPAREN
;

Inner:
	{Inner}
	parameter=IDENTIFIER
	(ASSIGNASSINGLE assign=Element
	|
	ASSIGNASLIST assignList+=Element (COMMA assignList+=Element)*
	|
	ASSIGNASSTRING value=STRING
	) 
;

terminal PACKAGE: 'package';
terminal LANGUAGE: 'language';
terminal POINT: '.';
terminal SOURCE: 'source';
terminal SRCTEXT: 'text';
terminal SRCFILE: 'file';
terminal LEXER: 'lexer-tokens';
terminal LEFTPAREN: '(';
terminal RIGHTPAREN: ')';
terminal ASSIGNASSINGLE: '=';
terminal ASSIGNASLIST: '+=';
terminal ASSIGNASSTRING: '++';
terminal COMMA: ',';
terminal IDENTIFIER: ID;
