<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="preprocess" nsURI="http://www.jku.at/weiner/c/preprocess/Preprocess"
    nsPrefix="preprocess">
  <eClassifiers xsi:type="ecore:EClass" name="GroupOpt">
    <eStructuralFeatures xsi:type="ecore:EReference" name="lines" upperBound="-1"
        eType="#//SourceCodeLine" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SourceCodeLine"/>
  <eClassifiers xsi:type="ecore:EClass" name="IncludeDirective">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="string" eType="ecore:EDataType ../../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="unit" eType="ecore:EClass ../../../at.jku.weiner.c.common/model/custom/Common.ecore#//TranslationUnit"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="next" eType="ecore:EDataType ../../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DefineDirective">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ident" eType="ecore:EDataType ../../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IdentifierList">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ident" unique="false" upperBound="-1"
        eType="ecore:EDataType ../../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="variadic" eType="ecore:EDataType ../../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="varID" eType="ecore:EDataType ../../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ErrorDirective">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="msg" eType="ecore:EDataType ../../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WarningDirective">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="msg" eType="ecore:EDataType ../../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnDefineDirective">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ident" eType="ecore:EDataType ../../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConditionalDirective">
    <eStructuralFeatures xsi:type="ecore:EReference" name="conditional" eType="#//IfAbstractConditional"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elifs" upperBound="-1"
        eType="#//ElIfConditional" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="else" eType="#//ElseConditional"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="branchTaken" eType="#//IfAbstractConditional"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IfConditional" eSuperTypes="#//IfAbstractConditional">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="ecore:EClass ../../../at.jku.weiner.c.common/model/custom/Common.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IfDefConditional" eSuperTypes="#//IfAbstractConditional">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ident" eType="ecore:EDataType ../../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IfNotDefConditional" eSuperTypes="#//IfAbstractConditional">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ident" eType="ecore:EDataType ../../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ElIfConditional" eSuperTypes="#//IfAbstractConditional">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="ecore:EClass ../../../at.jku.weiner.c.common/model/custom/Common.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ElseConditional" eSuperTypes="#//IfAbstractConditional"/>
  <eClassifiers xsi:type="ecore:EClass" name="PragmaDirective">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pragma" eType="ecore:EDataType ../../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NullDirective"/>
  <eClassifiers xsi:type="ecore:EClass" name="Preprocess" eSuperTypes="../../../at.jku.weiner.c.common/model/custom/Common.ecore#//Preprocess">
    <eStructuralFeatures xsi:type="ecore:EReference" name="group" eType="#//GroupOpt"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GroupOpt2" eSuperTypes="#//GroupOpt"/>
  <eClassifiers xsi:type="ecore:EClass" name="PreprocessorDirectives" eSuperTypes="#//SourceCodeLine">
    <eStructuralFeatures xsi:type="ecore:EReference" name="directive" eType="ecore:EClass ../../../org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DefineObjectMacro" eSuperTypes="#//DefineDirective">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="string" eType="ecore:EDataType ../../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DefineFunctionLikeMacro" eSuperTypes="#//DefineDirective">
    <eStructuralFeatures xsi:type="ecore:EReference" name="list" eType="#//IdentifierList"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="string" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NewLineLine" eSuperTypes="#//SourceCodeLine"/>
  <eClassifiers xsi:type="ecore:EClass" name="Code" eSuperTypes="#//SourceCodeLine">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="code" eType="ecore:EDataType ../../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrimaryExpression" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defined" eType="ecore:EDataType ../../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ident" eType="ecore:EDataType ../../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="const" eType="ecore:EDataType ../../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expr" eType="ecore:EClass ../../../at.jku.weiner.c.common/model/custom/Common.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parentheses" eType="ecore:EDataType ../../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IfAbstractConditional">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="branchTaken" eType="ecore:EDataType ../../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="group" eType="#//GroupOpt"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression" eSuperTypes="../../../at.jku.weiner.c.common/model/custom/Common.ecore#//Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="LineDirective">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="line" eType="ecore:EDataType ../../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" eType="ecore:EDataType ../../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
