/*
 * generated by Xtext 2.9.0-SNAPSHOT
 */
package at.jku.weiner.c.common.formatting2

import at.jku.weiner.c.common.services.CommonGrammarAccess
import com.google.inject.Inject
import org.eclipse.xtext.formatting2.AbstractFormatter2
import org.eclipse.xtext.formatting2.IFormattableDocument

class CommonFormatter extends AbstractFormatter2 {
	
	@Inject extension CommonGrammarAccess
	
	override format(Object obj, IFormattableDocument document) {
		throw new UnsupportedOperationException("TODO: auto-generated method stub")
	}
	
}
