/*
 [The "BSD licence"]
 Copyright (c) 2013 Sam Harwell
 Copyright (c) 2015 Harald Weiner
 All rights reserved.

 Redistribution and use in source and binary forms, with or without
 modification, are permitted provided that the following conditions
 are met:
 1. Redistributions of source code must retain the above copyright
    notice, this list of conditions and the following disclaimer.
 2. Redistributions in binary form must reproduce the above copyright
    notice, this list of conditions and the following disclaimer in the
    documentation and/or other materials provided with the distribution.
 3. The name of the author may not be used to endorse or promote products
    derived from this software without specific prior written permission.

 THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
 INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/
grammar at.jku.weiner.cpreprocess.CPreprocess // with org.eclipse.xtext.common.Terminals
//hidden(LINEBREAK)

import "http://www.eclipse.org/emf/2002/Ecore" as ecore

generate cPreprocess "http://www.jku.at/weiner/cpreprocess/CPreprocess"

Model:
	{Model}
	(units+=TranslationUnit);
	
TranslationUnit:
	{TranslationUnit}
	(	lines+=PreprocessorDirectives
		|
		lines+=NewLineLine
		|	
		lines+=Code
	)*
;

PreprocessorDirectives returns SourceCodeLine:
	{PreprocessorDirectives}
	// HASH
	(
			directive=IncludeDirective
		|	directive=DefineDirective
		|	directive=UnDefineDirective
		|	directive=ErrorDirective
		|	directive=PragmaDirective
	)
	NEWLINE
;

IncludeDirective:
	{IncludeDirective}
	INCLUDE string=MyCodeLine
;

DefineDirective:
	{DefineDirective}
	DEFINE id=ID WS+ string=MyCodeLine
;

UnDefineDirective:
	{UnDefineDirective}
	UNDEF
;

ErrorDirective:
	{ErrorDirective}
	ERROR msg=MYCODE
;

PragmaDirective:
	{PragmaDirective}
	PRAGMA
;

NewLineLine returns SourceCodeLine:
	{NewLineLine}
	NEWLINE
;

Code returns SourceCodeLine:
	{Code}
	code=MyCodeLine
	NEWLINE
;

MyCodeLine returns ecore::EString:
	(MYCODE | ID)+
;


// lexer tokens
terminal fragment LINEFEED: '\n';
terminal fragment CARRIAGERETURN: '\r';
terminal NEWLINE: (CARRIAGERETURN | LINEFEED);
terminal fragment BACKSLASH: '\\';
terminal fragment LINEBREAK: (BACKSLASH NEWLINE)+;
terminal WS: (' ' | '\t' | LINEBREAK);
terminal fragment HASH: '#';
terminal DEFINE:	HASH WS* 'define' WS+;
terminal UNDEF:		HASH WS* 'undef' WS+;
terminal INCLUDE:	HASH WS* 'include' WS+;
terminal ERROR:		HASH WS* 'error' WS+;
terminal PRAGMA:	HASH WS* 'pragma' WS+;

terminal ID: IDENTIFIER;
terminal fragment IDENTIFIER:
	LETTER (LETTER|'0'..'9')*
;

terminal fragment LETTER:
	'$'
	|	'A'..'Z'
	|	'a'..'z'
	|	'_'
;

terminal fragment NO_CODE_START:
	NEWLINE | HASH
;

terminal MYCODE:
	!(HASH|CARRIAGERETURN|LINEFEED)
	(!(CARRIAGERETURN|LINEFEED))*
;
