/*
 [The "BSD licence"]
 Copyright (c) 2013 Sam Harwell
 Copyright (c) 2015 Harald Weiner
 All rights reserved.

 Redistribution and use in source and binary forms, with or without
 modification, are permitted provided that the following conditions
 are met:
 1. Redistributions of source code must retain the above copyright
    notice, this list of conditions and the following disclaimer.
 2. Redistributions in binary form must reproduce the above copyright
    notice, this list of conditions and the following disclaimer in the
    documentation and/or other materials provided with the distribution.
 3. The name of the author may not be used to endorse or promote products
    derived from this software without specific prior written permission.

 THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
 INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/
grammar at.jku.weiner.c.preprocess.Preprocess
with at.jku.weiner.c.common.Common
hidden(BLOCK_COMMENT,LINE_COMMENT,LINEBREAK)

import "http://www.eclipse.org/emf/2002/Ecore" as ecore

generate preprocess "http://www.jku.at/weiner/c/preprocess/Preprocess"

Model:
	{Model}
	(units+=TranslationUnit)
;
	
TranslationUnit:
	{TranslationUnit}
	group=GroupOpt2
;

GroupOpt:
	{GroupOpt}
	(
		lines+=GroupOptTemp1
		NEWLINE
	)*
;

GroupOpt2 returns GroupOpt:
	{GroupOpt2}
	(
		lines+=GroupOptTemp1
		NEWLINE
	)*
	(
		lines+=GroupOptTemp2
	)?
;

GroupOptTemp1 returns SourceCodeLine:
		PreprocessorDirectives
	|	NewLineLine	
	|	Code
;

GroupOptTemp2 returns SourceCodeLine:
		PreprocessorDirectives
	|	Code
;

PreprocessorDirectives returns SourceCodeLine:
	{PreprocessorDirectives}
	WHITESPACE* HASH WHITESPACE*
	(
			directive=IncludeDirective
		|	directive=DefineDirective
		|	directive=ErrorDirective
		|	directive=WarningDirective
		|	directive=UnDefineDirective
		|	directive=ConditionalDirective
		|	directive=PragmaDirective
		|	directive=NullDirective
	)
	//(NEWLINE)
;

IncludeDirective:
	{IncludeDirective}
	INCLUDE WHITESPACE+ string=MyCodeLine
;

DefineDirective:
		DefineObjectMacro
	|	DefineFunctionLikeMacro
;

DefineObjectMacro returns DefineDirective:
	{DefineObjectMacro}
	DEFINE WHITESPACE+ id=ID
		(WHITESPACE+ string=MyDefineLine)?
;

DefineFunctionLikeMacro returns DefineDirective:
	{DefineFunctionLikeMacro}
	DEFINE WHITESPACE+ id=ID 
	SKW_LEFTPAREN WHITESPACE*
		(list=IdentifierList)?
	SKW_RIGHTPAREN
	
	(WHITESPACE+
	string=MyDefineLine)? 
;

IdentifierList:
	{IdentifierList}
	id+=ID (SKW_COMMA WHITESPACE* id+=ID)*
;

ErrorDirective:
	{ErrorDirective}
	ERROR WHITESPACE* (msg=MyCodeLine)?
;

WarningDirective:
	{WarningDirective}
	WARNING WHITESPACE* (msg=MyCodeLine)?
;

UnDefineDirective:
	{UnDefineDirective}
	UNDEF WHITESPACE+ id=ID WHITESPACE*
;

ConditionalDirective:
	{ConditionalDirective}
	(conditional=
		(		IfConditional	
			|	IfDefConditional
			|	IfNotDefConditional
		)
	)
	(elifs+=ElIfConditional)*
	(else=ElseConditional)?
	WHITESPACE* HASH WHITESPACE* ENDIF WHITESPACE*
;

IfConditional:
	{IfConditional}
	IF WHITESPACE+ expression=Common::ConstantExpression WHITESPACE* NEWLINE
		group=GroupOpt
;

IfDefConditional:
	{IfDefConditional}
	IFDEF WHITESPACE+ id=ID WHITESPACE* NEWLINE
		group=GroupOpt
;

IfNotDefConditional:
	{IfNotDefConditional}
	IFNOTDEF WHITESPACE+ id=ID WHITESPACE* NEWLINE
		group=GroupOpt
;

ElIfConditional:
	{ElIfConditional}
	(WHITESPACE* HASH WHITESPACE* ELIF) WHITESPACE+ expression=Common::ConstantExpression WHITESPACE* NEWLINE
		group=GroupOpt
;

ElseConditional:
	{ElseConditional}
	WHITESPACE* HASH WHITESPACE* ELSE WHITESPACE* NEWLINE
		group=GroupOpt
;

PragmaDirective:
	{PragmaDirective}
	PRAGMA
;

NullDirective:
	{NullDirective}
;

NewLineLine returns SourceCodeLine:
	{NewLineLine}
	//(NEWLINE)
;

Code returns SourceCodeLine:
	{Code}
	code=MyCodeLineExtended
	//(NEWLINE)
;

MyCode returns ecore::EString:
	ID|SPECIAL|INCLUDE|DEFINE|ERROR|PRAGMA
	|IFDEF|ENDIF|IFNOTDEF|IF|DEFINED
	|SpecialKeywords|Constant1
;

MyDefineLine returns ecore::EString:
	(MyCode|WHITESPACE|HASH)*
;

MyCodeLine returns ecore::EString:
	(MyCode|WHITESPACE)+
;

MyCodeLineExtended returns ecore::EString:
		MyCodeLineExtendedWSOnly
	|	MyCodeLineExtendedNormal
;

MyCodeLineExtendedWSOnly returns ecore::EString:
	WHITESPACE+
;

MyCodeLineExtendedNormal returns ecore::EString:
	WHITESPACE* MyCode+ (MyCodeLine|HASH)*
;

// expressions
PrimaryExpression returns Expression:
	{PrimaryExpression}
	(
		(defined?=DEFINED)? id=ID
	|	(defined?=DEFINED)? SKW_LEFTPAREN id=ID SKW_RIGHTPAREN
	|	const=Constant1
	//|	string+=STRING_LITERAL+ // reachable over Constant!
	|	SKW_LEFTPAREN expr=Expression SKW_RIGHTPAREN
	)
;

// lexer tokens
terminal HASH: '#';
terminal INCLUDE: 'include';
terminal DEFINE: 'define';
terminal ERROR: 'error';
terminal WARNING: 'warning';
terminal UNDEF: 'undef';
terminal IF: 'if';
terminal DEFINED: 'defined';
terminal IFDEF: 'ifdef';
terminal IFNOTDEF: 'ifndef';
terminal ELIF: 'elif';
terminal ELSE: 'else';
terminal ENDIF: 'endif';
terminal PRAGMA: 'pragma';

// special keywords
// ... see common
//terminal END_OF_FILE: EOF;
terminal NEWLINE: Common::NEWLINE;// | END_OF_FILE;
