/**
 * generated by Xtext 2.9.0-SNAPSHOT
 */
package at.jku.weiner.cpreprocess;

import at.jku.weiner.cpreprocess.CPreprocessStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class CPreprocessStandaloneSetup extends CPreprocessStandaloneSetupGenerated {
  public static void doSetup() {
    CPreprocessStandaloneSetup _cPreprocessStandaloneSetup = new CPreprocessStandaloneSetup();
    _cPreprocessStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
