/*
 * generated by Xtext 2.9.0-SNAPSHOT
 */
package at.jku.weiner.c.parser.ui;

import at.jku.weiner.c.parser.ui.internal.ParserActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ParserExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return ParserActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return ParserActivator.getInstance().getInjector(ParserActivator.AT_JKU_WEINER_C_PARSER_PARSER);
	}
	
}
