/**
 * generated by Xtext 2.9.0-SNAPSHOT
 */
package at.jku.weiner.c.parser.ui.contentassist;

import at.jku.weiner.c.parser.ui.contentassist.AbstractParserProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class ParserProposalProvider extends AbstractParserProposalProvider {
}
