/**
 * generated by Xtext 2.9.0-SNAPSHOT
 */
package at.jku.weiner.kefax.dotconfig.ui;

import at.jku.weiner.kefax.dotconfig.ui.AbstractDotconfigUiModule;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
/* @FinalFieldsConstructor */@SuppressWarnings("all")
public class DotconfigUiModule extends AbstractDotconfigUiModule {
}
