/*
 * generated by Xtext 2.9.0.v201509120608
 */
package org.xtext.example.mydsl1.formatting2

import com.google.inject.Inject
import org.eclipse.xtext.formatting2.AbstractFormatter2
import org.eclipse.xtext.formatting2.IFormattableDocument
import org.xtext.example.mydsl1.myDsl.Greeting
import org.xtext.example.mydsl1.myDsl.Model
import org.xtext.example.mydsl1.services.MyDslGrammarAccess

class MyDslFormatter extends AbstractFormatter2 {
	
	@Inject extension MyDslGrammarAccess

	def dispatch void format(Model model, extension IFormattableDocument document) {
		// TODO: format HiddenRegions around keywords, attributes, cross references, etc. 
		for (Greeting greetings : model.getGreetings()) {
			format(greetings, document);
		}
	}
}
