/**
 * generated by Xtext 2.9.0-SNAPSHOT
 */
package at.jku.weiner.c.parser;

import at.jku.weiner.c.parser.AbstractParserRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class ParserRuntimeModule extends AbstractParserRuntimeModule {
}
