/*
 * generated by Xtext 2.9.0-SNAPSHOT
 */
package at.jku.weiner.xtexttest.generator

import org.eclipse.emf.ecore.resource.Resource
import org.eclipse.xtext.generator.IFileSystemAccess
import org.eclipse.xtext.generator.IGenerator
import at.jku.weiner.xtexttest.xtextTest.XtextTest

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
class XtextTestGenerator implements IGenerator {

	override void doGenerate(Resource resource, IFileSystemAccess fsa) {
		val generator = new MyGenerator();
		fsa.generateFile('XtextTest.java',
			generator.generate( 
			resource.allContents.filter(typeof(XtextTest)).head)
//			resource.allContents
//				.filter(typeof(Greeting))
//				.map[name]
//				.join(', '))
		);
	}

}
